import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { GamePlayback } from './GamePlayback'

beforeEach(() => vi.useFakeTimers())
afterEach(() => vi.useRealTimers())

describe('active playback clock', () => {
  it('preserves remaining time across repeated pauses and resumes only by explicit action', async () => {
    const playback = new GamePlayback()
    playback.setActive(true)
    const done = vi.fn()
    playback.schedule(done, 1000)
    await vi.advanceTimersByTimeAsync(275)
    playback.setBlocked('hidden', true)
    const frozen = playback.now()
    await vi.advanceTimersByTimeAsync(10000)
    expect(playback.now()).toBe(frozen)
    expect(done).not.toHaveBeenCalled()
    expect(playback.resume()).toBe(false)
    playback.setBlocked('hidden', false)
    await vi.advanceTimersByTimeAsync(10000)
    expect(done).not.toHaveBeenCalled()
    expect(playback.resume()).toBe(true)
    await vi.advanceTimersByTimeAsync(300)
    playback.pause()
    await vi.advanceTimersByTimeAsync(10000)
    playback.resume()
    await vi.advanceTimersByTimeAsync(424)
    expect(done).not.toHaveBeenCalled()
    await vi.advanceTimersByTimeAsync(1)
    expect(done).toHaveBeenCalledOnce()
    expect(playback.now()).toBe(1000)
  })
  it('requires all blockers to clear and cancels queued callbacks without executing them', async () => {
    const playback = new GamePlayback()
    playback.setActive(true)
    const aborted = new AbortController(), done = vi.fn()
    playback.setBlocked('focus', true)
    playback.setBlocked('dialog', true)
    const waiting = playback.wait(650, aborted.signal)
    playback.whenRunning(done, aborted.signal)
    playback.setBlocked('focus', false)
    expect(playback.resume()).toBe(false)
    aborted.abort()
    expect(await waiting).toBe(false)
    playback.setBlocked('dialog', false)
    playback.resume()
    await vi.advanceTimersByTimeAsync(1000)
    expect(done).not.toHaveBeenCalled()
    expect(vi.getTimerCount()).toBe(0)
  })
  it('lets inactive screens return without creating a paused duel and cancels all old work', async () => {
    const playback = new GamePlayback()
    playback.setBlocked('hidden', true)
    playback.setBlocked('hidden', false)
    expect(playback.paused).toBe(false)
    playback.setActive(true)
    playback.pause()
    const done = vi.fn(), waiting = playback.wait(100)
    playback.whenRunning(done)
    playback.cancelAll()
    expect(await waiting).toBe(false)
    playback.setActive(false)
    expect(playback.paused).toBe(false)
    await vi.advanceTimersByTimeAsync(200)
    expect(done).not.toHaveBeenCalled()
  })
})
